<?php
/**
 * @author Maxim Cherednyk <maks757q@gmail.com, +380639960375>
 */

namespace maks757\egallery\widgets\show_images;

use yii\base\Widget;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
class Gallery extends Widget
{
    public $url = '/gallery/image/upload-image';
    public $object;
    private $images;
    public $show_name = true;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        /** @var $object ActiveRecord */
        $object = $this->object;
        $this->images = \maks757\egallery\entities\Gallery::findAll(['key' => md5($object->className()), 'object_id' => $object->getPrimaryKey()]);
    }

    public function run()
    {
        /** @var $object ActiveRecord */
        $object = $this->object;
        ArrayHelper::multisort($this->images, 'position');
        return $this->render('image', [
            'images' => $this->images,
            'url' => Url::toRoute($this->url, true),
            'show_name' => $this->show_name,
            'object' => $object
        ]);
    }
}